  
export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_RESPONSE ="LOGIN_RESPONSE";
export const LOGIN_ERROR ="LOGIN_ERROR";
export const LOGIN_RESPONSE_ERROR ="LOGIN_RESPONSE_ERROR";
export const MAKE_LOGIN_RESPOSE_EMPTY ="MAKE_LOGIN_RESPOSE_EMPTY";
const GET_SUCESS="GET_SUCESS";
const ADD_TO_CART="ADD_TO_CART";
const REMOVE_FROM_CART="REMOVE_FROM_CART";
const BUTTON_SHOW='BUTTON_SHOW';
const PRODUCT_GET="PRODUCT_GET";
const BLOG="BLOG";
export {BLOG,ADD_TO_CART,REMOVE_FROM_CART,BUTTON_SHOW,PRODUCT_GET};
const ADD_TO_WISHLIST="ADD_TO_WISHLIST";
const REMOVE_FROM_WISHLIST="REMOVE_FROM_WISHLIST";
export {ADD_TO_WISHLIST,REMOVE_FROM_WISHLIST,GET_SUCESS};
export const HOME_PRODUCT_VIEW="HOME_PRODUCT_VIEW";
export const PRODUCT = "PRODUCT";
export const REMOVE_LOGIN_RESPONSE ="REMOVE_LOGIN_RESPONSE";
export const UPDATE_FEATURE_ITEMS ="UPDATE_FEATURE_ITEMS";
export const PRODUCT_GET_STARTED="PRODUCT_GET_STARTED";
export const PRODUCT_FETCH_FAILED="PRODUCT_FETCH_FAILED";

